[tool.poetry]
name = "ghostty-discord-bot"
version = "0.1.0"
description = ""
authors = ["Mitchell Hashimoto <m@mitchellh.com>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.11"
