name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  UV_VERSION: 0.8.15
  UV_NO_SYNC: 1
  UV_LOCKED: 1
  PY_COLORS: 1

jobs:
  ci:
    if: github.repository == 'ghostty-org/discord-bot'
    runs-on: namespace-profile-ghostty-sm
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: Setup uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6  # v6.6.1
        with:
          version: ${{ env.UV_VERSION }}
      - name: Environment
        id: sync
        run: uv sync
      - name: taplo (TOML formatting)
        if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
        run: uv run taplo fmt --check --diff pyproject.toml
      - name: ruff format
        if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
        run: uv run ruff format --diff
      - name: ruff lint
        if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
        run: uv run ruff check --output-format github
      - name: pytest
        if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
        run: uv run pytest -vv
      - name: basedpyright
        if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
        run: uv run basedpyright app tests
