on:
  push:
    branches:
      - main
  pull_request:

env:
  PY_COLORS: 1
  UV_VERSION: 0.6.1

name: Ruff
jobs:
  check-ruff:
    if: github.repository == 'ghostty-org/discord-bot'
    runs-on: namespace-profile-ghostty-sm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
      - name: Install project
        run: uv sync
      - name: Lint code
        run: |
          uv run ruff check
          uv run ruff format --check
